Fantom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls')),
    path('detail/<int:pk>/<slug:slug>',include('posts.urls')),
    path('category/<int:pk>/<slug:slug>',include('posts.urls')),
    path('tags/<slug:slug>',include('posts.urls')),

    path('users/',include('users.urls')),
]

posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

urlpatterns = [
    path('',IndexView.as_view(),name="index"),
    path('detail/<int:pk>/<slug:slug>',PostDetail.as_view(),name="detail"),
    path('category/<int:pk>/<slug:slug>',CategoryView.as_view(),name="category_detail"),
    path('tags/<slug:slug>',TagDetail.as_view(),name="tag_detail"),
    path('create-post/',CreatePostView.as_view(),name="create_post"),
    path('update-post/<int:pk>/<slug:slug>',UpdatePostView.as_view(),name="update_post"),
    path('delete-post/<int:pk>/<slug:slug>',DeletePostView.as_view(),name="delete_post"),
    path('search/',SearchView.as_view(),name='search'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as authViews
app_name = "users"
urlpatterns = [
    path('',UserListView.as_view(),name="user_list"),
    path('register/',RegisterView.as_view(),name="register"),
    path('login/',UserLoginView.as_view(),name="login"),
    path('logout/',UserLogoutView.as_view(),name="logout"),
    path('change-password/',authViews.PasswordChangeView.as_view(),name="password_change"),
    path('change-password-done/',authViews.PasswordChangeDoneView.as_view(),name="change_password_done"),
    path('update-profile/<slug:slug>/',UserProfileUpdateView.as_view(),name="update_profile"),
    path('my-profile/',UserProfileView.as_view(),name="my-profile"),
    path('<int:pk>/',UserPostView.as_view(),name="user_posts"),

]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png">
        <title>Fantom Blog</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/linericon/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/lightbox/simpleLightbox.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/nice-select/css/nice-select.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/animate-css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/jquery-ui/jquery-ui.css' %}">
        <!-- main css -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">


    </head>
    <body>
        
        <!--================Header Menu Area =================-->
        <header class="header_area">
            <div class="logo_part">
            	<div class="container">
            		<a class="logo" href="{% url 'index' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
            	</div>
            </div>
			<div class="main_menu">
				<nav class="navbar navbar-expand-lg navbar-light">
					<div class="container">
						<!-- Brand and toggle get grouped for better mobile display -->
						<a class="navbar-brand logo_h" href="index.html"><img src="{% static 'img/logo.png' %}" alt=""></a>
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<!-- Collect the nav links, forms, and other content for toggling -->
						<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
							<ul class="nav navbar-nav menu_nav">
								<li class="nav-item "><a class="nav-link" href="{% url 'index' %}">Home</a></li> 
                                <li class="nav-item "><a class="nav-link" href="{% url 'users:user_list' %}">Users</a></li> 
								
								
                                {% if user.is_authenticated %}
                                <li class="nav-item submenu dropdown">
									<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
									<ul class="dropdown-menu">
										<li class="nav-item"><a class="nav-link" href="{% url 'create_post' %}">Add Post</a></li>
										
                                        <li class="nav-item"><a class="nav-link" href="{% url 'users:my-profile' %}">My Profile</a></li>
                             
                                        <li class="nav-item"><a class="nav-link" href="{% url 'users:password_change' %}">Change Password </a></li>
                                        <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">Log Out</a></li>
                                        
									</ul>
								</li> 
                                
                                {% else %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}">Register</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">Login</a></li>
                                {% endif %}
								
							</ul>
							<ul class="nav navbar-nav navbar-right ml-auto">
								
                                <form action="{% url 'search' %}" method="get">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search Posts" name="q">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button"><i class="lnr lnr-magnifier"></i></button>
                                    </span>
                                </div>
                                </form>
							</ul>
						</div> 
					</div>
				</nav>
			</div>
        </header>
        <!--================Header Menu Area =================-->

        {% block content %}

        
        {% endblock%}






               <!--================ start footer Area  =================-->	
        <footer class="footer-area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3  col-md-6 col-sm-6">
                        <div class="single-footer-widget">
                            <h6 class="footer_title">About Us</h6>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua.</p>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="single-footer-widget">
                            <h6 class="footer_title">Newsletter</h6>
                            <p>Stay updated with our latest trends</p>		
                            <div id="mc_embed_signup">
                                <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscribe_form relative">
                                    <div class="input-group d-flex flex-row">
                                        <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
                                        <button class="btn sub-btn"><span class="lnr lnr-arrow-right"></span></button>		
                                    </div>									
                                    <div class="mt-10 info"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="single-footer-widget instafeed">
                            <h6 class="footer_title">Instagram Feed</h6>
                            <ul class="list instafeed d-flex flex-wrap">
                                <li><img src="{% static 'img/instagram/Image-01.jpg' %}" alt=""></li>
                                <li><img src="{% static 'img/instagram/Image-02.jpg' %}" alt=""></li>
                                <li><img src="{% static 'img/instagram/Image-03.jpg' %}" alt=""></li>
                                <li><img src="{% static 'img/instagram/Image-04.jpg' %}" alt=""></li>
                                <li><img src="{% static 'img/instagram/Image-05.jpg' %}" alt=""></li>
                                <li><img src="{% static 'img/instagram/Image-06.jpg' %}" alt=""></li>
                                <li><img src="{% static 'img/instagram/Image-07.jpg' %}" alt=""></li>
                                <li><img src="{% static 'img/instagram/Image-08.jpg' %}" alt=""></li>
                            </ul>
                        </div>
                    </div>	
                    <div class="col-lg-2 col-md-6 col-sm-6">
                        <div class="single-footer-widget f_social_wd">
                            <h6 class="footer_title">Follow Us</h6>
                            <p>Let us be social</p>
                            <div class="f_social">
                            	<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-dribbble"></i></a>
								<a href="#"><i class="fa fa-behance"></i></a>
                            </div>
                        </div>
                    </div>						
                </div>
                <div class="row footer-bottom d-flex justify-content-between align-items-center">
                    <p class="col-lg-12 footer-text text-center"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                </div>
            </div>
        </footer>
		<!--================ End footer Area  =================-->
      
        
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/popper.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/stellar.js' %}"></script>
        <script src="{% static 'vendors/lightbox/simpleLightbox.min.js' %}"></script>
        <script src="{% static 'vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
        <script src="{% static 'vendors/isotope/isotope-min.js' %}"></script>
        <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
        <script src="{% static 'vendors/jquery-ui/jquery-ui.js' %}"></script>
        <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
        <script src="{% static 'js/mail-script.js' %}"></script>
        <script src="{% static 'js/theme.js' %}"></script>
    </body>
</html>

templates/category_detail.html
{% extends "base.html" %}

{% load static %}

        {% block content %}
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Category</h2>
						<div class="page_link">
							<a href="{% url 'index' %}">Home</a>
							<a href="#">{{ category.title }}</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Blog Area =================-->
        <section class="blog_area p_120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="blog_left_sidebar">
							{% for post in posts %}
                            <article class="blog_style1">
                            	<div class="blog_img">
                            		<img class="img-fluid" src="{{ post.image.url }}" style="width:800px;height:400px;" alt="">
                            	</div>
                            	<div class="blog_text">
									<div class="blog_text_inner">
										<a class="cat" href="#">{{ post.category }}</a>
										<a href="{% url 'detail' post.pk post.slug %}"><h4>{{ post.title }}</h4></a>
										<p>{{ post.content | truncatechars:150 }}</p>
										<div class="date">
											<a href="#"><i class="fa fa-calendar" aria-hidden="true"></i>{{ post.publishing_date }}</a>
											<a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i> 05</a>
										</div>	
									</div>
                            	</div>
                            </article>
							{% endfor %}
                            
								{% if is_paginated %}

					<nav class="blog-pagination justify-content-center d-flex">
		                        <ul class="pagination">
								{% if page_obj.has_previous %}
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>

									{% endif %}

									{% for i in paginator.page_range %}

									{% if page_obj.number == i %}



		                            <li class="page-item active"><a href="#" class="page-link">{{ i }}</a></li>
									{% else %}
		                            <li class="page-item "><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
									{% endif %}
									
									{% endfor %}

									{% if page_obj.has_next %}
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>


									{% endif %}
		                        </ul>
		                    </nav>
							{% endif %}

                        </div>
                    </div>
                    
		{% include 'right_side.html' %}

                </div>
            </div>
        </section>
        <!--================Blog Area =================-->
      {% endblock %}

templates/create-post.html
{% extends "base.html" %}

{% load static %}

        {% block content %}
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Login</h2>
						<div class="page_link">
							<a href="{% url 'index' %}">Home</a>
							<a href="#">{{ category.title }}</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Blog Area =================-->
        <section class="blog_area p_120">
            <div class="container">
                <div class="row">


          
                    <div class="col-lg-8">


                        <div class="blog_left_sidebar">

                             <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <h2 style="color:#192A56;text-align:center;">Add Post</h2>
                            </br>

                                    {% if form.errors %}

                                        <div class="errors">

                                            <div class="inner">
                                                <p style="color: red;">Please Correct The Errors Below</p>
                                                    <ul>
                                                    {% for field in form %}
                                                        {% if field.errors %}
                                                           
                                                            <li>  {{ field.errors|striptags }} </li>

                                                        {% endif %}
                                                    {% endfor %}
                                                    </ul>
                                            </div>
                                        </div>
                                    {% endif %}


                            <div class="mt-10">
                            {% for field in form %}
                                
                                    {{ field }}
                                    </br>
                            {% endfor %}
                            
                            </div>
                            </br>
                            <div class="mt-10">
                            <input type="text" name="tag" placeholder="Add Tag"
                             onfocus="this.placeholder = ''" onblur="this.placeholder = 'Add Tag'" 
                             required="" class="single-input">
                            </div>

                            </br>
                          
                          <div class="container">
                            <input type="submit" value="Add" class="genric-btn success circle" style="font-size: 15px;margin-left:320px;">
                        </div>
                        </form>

                    
                        </div>
                    </div>
                    
                   
		{% include 'right_side.html' %}

                </div>
            </div>
        </section>
        <!--================Blog Area =================-->
      {% endblock %}

templates/my-profile.html
{% extends "base.html" %}

{% load static %}

        {% block content %}
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						
						<div class="page_link">
                        </br>
							<img src="{{ userprofile.image.url }}">
                            <h4 style="color:white;">{{ userprofile.user.username }}</h4>
                               <p style="color:white;">Birthday: {{ userprofile.birth_day }}</p>
                                  <p style="color:white;">{{ userprofile.bio | linebreaks }} </p>
                                
                                  <a href="{% url 'users:update_profile' userprofile.slug %}" style="margin-bottom:30px;" class="genric-btn info circle">Update Profile</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Blog Area =================-->
        <section class="blog_area p_120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="blog_left_sidebar">
							{% for post in userposts %}
                            <article class="blog_style1">
                            	<div class="blog_img">
                            		<img class="img-fluid" src="{{ post.image.url }}" style="width:800px;height:400px;" alt="">
                            	</div>
                            	<div class="blog_text">
									<div class="blog_text_inner">
										<a class="cat" href="#">{{ post.category }}</a>
										<a href="{% url 'detail' post.pk post.slug %}"><h4>{{ post.title }}</h4></a>
										<p>{{ post.content | truncatechars:150 }}</p>
										<div class="date">
											<a href="#"><i class="fa fa-calendar" aria-hidden="true"></i>{{ post.publishing_date }}</a>
											<a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i> 05</a>
										</div>	
									</div>
                            	</div>
                            </article>
							{% endfor %}
                            
								{% if is_paginated %}

					<nav class="blog-pagination justify-content-center d-flex">
		                        <ul class="pagination">
								{% if page_obj.has_previous %}
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>

									{% endif %}

									{% for i in paginator.page_range %}

									{% if page_obj.number == i %}



		                            <li class="page-item active"><a href="#" class="page-link">{{ i }}</a></li>
									{% else %}
		                            <li class="page-item "><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
									{% endif %}
									
									{% endfor %}

									{% if page_obj.has_next %}
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>


									{% endif %}
		                        </ul>
		                    </nav>
							{% endif %}

                        </div>
                    </div>
                    
		{% include 'right_side.html' %}

                </div>
            </div>
        </section>
        <!--================Blog Area =================-->
      {% endblock %}

templates/post-update.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

        {% block content %}
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Update Post</h2>
						<div class="page_link">
							<a href="{% url 'index' %}">Home</a>
							<a href="#">{{ category.title }}</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Blog Area =================-->
        <section class="blog_area p_120">
            <div class="container">
                <div class="row">


          
                    <div class="col-lg-8">


                        <div class="blog_left_sidebar">
                             <h2 style="color:#192A56;text-align:center;">Update Post</h2></br>
                             {% crispy form %}

                    
                        </div>
                    </div>
                    
                   
		{% include 'right_side.html' %}

                </div>
            </div>
        </section>
        <!--================Blog Area =================-->
      {% endblock %}

templates/user-list.html
{% extends "base.html" %}

{% load static %}

        {% block content %}
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Users</h2>
						<div class="page_link">
							<a href="{% url 'index' %}">Home</a>
							
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Blog Area =================-->
        <section class="blog_area p_120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="blog_left_sidebar" style="text-align: center;">
							{% for profile in profiles %}
                            <div class=container style="margin-bottom:30px;border-style:solid;border-width:2px;border-color:green;">

                                <img src="{{ profile.image.url }}" style="width:200px;height:200px;margin-top:15px;margin-bottom:15px;">
                                 <a href="{% url 'users:user_posts' profile.user.pk %}">  
                                 </br>
                                  <h4>{{ profile.user.username }}</h4></a>
                                <p>{{ profile.bio }}</p>
                                <p>{{ profile.birth_day }}</p>
                            </div>
							{% endfor %}
                            
								{% if is_paginated %}

					<nav class="blog-pagination justify-content-center d-flex">
		                        <ul class="pagination">
								{% if page_obj.has_previous %}
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>

									{% endif %}

									{% for i in paginator.page_range %}

									{% if page_obj.number == i %}



		                            <li class="page-item active"><a href="#" class="page-link">{{ i }}</a></li>
									{% else %}
		                            <li class="page-item "><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
									{% endif %}
									
									{% endfor %}

									{% if page_obj.has_next %}
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>


									{% endif %}
		                        </ul>
		                    </nav>
							{% endif %}

                        </div>
                    </div>
                    
		{% include 'right_side.html' %}

                </div>
            </div>
        </section>
        <!--================Blog Area =================-->
      {% endblock %}